# Meta Data for SEO

## Homepage
title = "Micro-Bench"
titleSeparator = ":"
titleAddition = "A Vision-Language Benchmark for Microscopy Understanding"
description = ""

## Open Graph
images = ["MEDALIGN_twitter_card.png"]
ogLocale = "en_US"
domainTLD = "doks.netlify.app"
titleHome = "Micro-Bench Project Website"

## Twitter Cards
twitterSite = "@Ale9806_"
twitterCreator = "@Ale9806_"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Doks"
schemaAuthor = "Henk Verlinde"
schemaAuthorTwitter = "https://twitter.com/Ale9806_"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/ale9806/"
schemaAuthorGitHub = "https://github.com/Ale9806"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = ""
schemaLinkedIn = ""
schemaGitHub = "https://github.com/Ale9806/uBench-website/"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2024 Alejandro Lozano"

# Alert
alert = false
alertText = "Like Micro-Bench? <a class=\"alert-link\" href=\"https://github.com/yeung-lab/u-Bench\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/Ale9806/Micro-Bench/"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = false
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  collapsibleSidebar = false
